spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:mysql://localhost:3306/bookmanager-jpa?useUnicode=true&characterEncoding=utf8
    username: bm
    password: 123qwe!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user_service
              uri: http://localhost:8081
              predicates:
                - Path=/api/member/**
              filters:
                - AddRequestHeader=x-member-id,test
                - AddRequestHeader=x-member-role,ROLE_ADMIN
            - id: auth_service
              uri: http://localhost:8082
              predicates:
                - Path=/auth/**
                - Path=/oauth2/**
logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
      springframework:
        cloud:
          openfeign: trace
        client:
          RestTemplate: debug
        security: trace

